//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gournal
    {
        public long inId { get; set; }
        public System.DateTime dtDate { get; set; }
        public string stUser { get; set; }
        public string stObject { get; set; }
        public string stComments { get; set; }
        public int inOperation { get; set; }
        public Nullable<byte> inGroup { get; set; }
        public Nullable<int> idobject { get; set; }
    }
}
